//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapWebSite.Resources.text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapWebSite.Resources.text.TextDictionary", typeof(TextDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the tool above to create a color palette.&lt;br /&gt;
        ///                Click the bar if you want to create a new color
        ///                and drag dots left or right to set the intervals.
        /// </summary>
        public static string HMenuCPArticle1 {
            get {
                return ResourceManager.GetString("HMenuCPArticle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your creation need a name :) chose it carefully, it must be &lt;b&gt;unique&lt;/b&gt;..
        /// </summary>
        public static string HMenuCPArticle2 {
            get {
                return ResourceManager.GetString("HMenuCPArticle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are almost done if you look here :) just press the button below if you&apos;re done..
        /// </summary>
        public static string HMenuCPArticle3 {
            get {
                return ResourceManager.GetString("HMenuCPArticle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string HMenuCPClosePicker {
            get {
                return ResourceManager.GetString("HMenuCPClosePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter a name....
        /// </summary>
        public static string HMenuCPNameInput {
            get {
                return ResourceManager.GetString("HMenuCPNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string HMenuCPSubmitButton {
            get {
                return ResourceManager.GetString("HMenuCPSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose colors.
        /// </summary>
        public static string HMenuCPSubtitle1 {
            get {
                return ResourceManager.GetString("HMenuCPSubtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a name.
        /// </summary>
        public static string HMenuCPSubtitle2 {
            get {
                return ResourceManager.GetString("HMenuCPSubtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string HMenuCPSubtitle3 {
            get {
                return ResourceManager.GetString("HMenuCPSubtitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your own color palette.
        /// </summary>
        public static string HMenuCPTitleText {
            get {
                return ResourceManager.GetString("HMenuCPTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create palette.
        /// </summary>
        public static string HMenuCreatePaletteText {
            get {
                return ResourceManager.GetString("HMenuCreatePaletteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to logout.
        /// </summary>
        public static string HMenuLogoutText {
            get {
                return ResourceManager.GetString("HMenuLogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HMenuSettingsText {
            get {
                return ResourceManager.GetString("HMenuSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a text file which contains points and upload them on server. &lt;br /&gt;
        ///            The name which you chose must be unique.
        ///            Dataset will be available for display after a service will process the text file..
        /// </summary>
        public static string HMenuUPInstructionText {
            get {
                return ResourceManager.GetString("HMenuUPInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload points.
        /// </summary>
        public static string HMenuUploadPointsText {
            get {
                return ResourceManager.GetString("HMenuUploadPointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert dataset name....
        /// </summary>
        public static string HMenuUPNameInput {
            get {
                return ResourceManager.GetString("HMenuUPNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file.
        /// </summary>
        public static string HMenuUPSelectFileButton {
            get {
                return ResourceManager.GetString("HMenuUPSelectFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload points.
        /// </summary>
        public static string HMenuUPTitle {
            get {
                return ResourceManager.GetString("HMenuUPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string HMenuUPUploadButton {
            get {
                return ResourceManager.GetString("HMenuUPUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file is required.....
        /// </summary>
        public static string HMenuUPWarningText {
            get {
                return ResourceManager.GetString("HMenuUPWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deformation rate.
        /// </summary>
        public static string HPIDeformationRateText {
            get {
                return ResourceManager.GetString("HPIDeformationRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated def. rate.
        /// </summary>
        public static string HPIEstimatedDefRateText {
            get {
                return ResourceManager.GetString("HPIEstimatedDefRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated height.
        /// </summary>
        public static string HPIEstimatedHeightText {
            get {
                return ResourceManager.GetString("HPIEstimatedHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HPIHeightText {
            get {
                return ResourceManager.GetString("HPIHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string HPIIDText {
            get {
                return ResourceManager.GetString("HPIIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string HPILatitudeText {
            get {
                return ResourceManager.GetString("HPILatitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string HPILongitudeText {
            get {
                return ResourceManager.GetString("HPILongitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plot to display.
        /// </summary>
        public static string HPINoPlotText {
            get {
                return ResourceManager.GetString("HPINoPlotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation.
        /// </summary>
        public static string HPIStandardDeviationText {
            get {
                return ResourceManager.GetString("HPIStandardDeviationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate info.
        /// </summary>
        public static string HPITitleText {
            get {
                return ResourceManager.GetString("HPITitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type here to search....
        /// </summary>
        public static string HPSCDSearchInput {
            get {
                return ResourceManager.GetString("HPSCDSearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose dataset.
        /// </summary>
        public static string HPSCDTitleText {
            get {
                return ResourceManager.GetString("HPSCDTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette name.
        /// </summary>
        public static string HPSCPHead1 {
            get {
                return ResourceManager.GetString("HPSCPHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string HPSCPHead2 {
            get {
                return ResourceManager.GetString("HPSCPHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string HPSCPHead3 {
            get {
                return ResourceManager.GetString("HPSCPHead3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string HPSCPPreviewButton {
            get {
                return ResourceManager.GetString("HPSCPPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type here to search.
        /// </summary>
        public static string HPSCPSearchText {
            get {
                return ResourceManager.GetString("HPSCPSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose palette.
        /// </summary>
        public static string HPSCPTitle {
            get {
                return ResourceManager.GetString("HPSCPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string HPSCPUseButton {
            get {
                return ResourceManager.GetString("HPSCPUseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LBackButton {
            get {
                return ResourceManager.GetString("LBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        public static string LFirstNameInput {
            get {
                return ResourceManager.GetString("LFirstNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name.
        /// </summary>
        public static string LLastNameInput {
            get {
                return ResourceManager.GetString("LLastNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an account? Click here to use the application without account.
        /// </summary>
        public static string LLoginAnonymousLink {
            get {
                return ResourceManager.GetString("LLoginAnonymousLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LLoginButton {
            get {
                return ResourceManager.GetString("LLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your credentials in the texboxes bellow to use the app &lt;br&gt;If you do not have an account, register.
        /// </summary>
        public static string LLoginMessage {
            get {
                return ResourceManager.GetString("LLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LLoginTitle {
            get {
                return ResourceManager.GetString("LLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string LPasswordInput {
            get {
                return ResourceManager.GetString("LPasswordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LRegisterButton {
            get {
                return ResourceManager.GetString("LRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to use the application. Enter the credentials bellow.
        /// </summary>
        public static string LRegisterMessage {
            get {
                return ResourceManager.GetString("LRegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LRegisterTitle {
            get {
                return ResourceManager.GetString("LRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string LSubmitRegisterButton {
            get {
                return ResourceManager.GetString("LSubmitRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string LUsernameInput {
            get {
                return ResourceManager.GetString("LUsernameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chosed an existent name for your dataset. Please chose another.
        /// </summary>
        public static string OverlayCDFailText {
            get {
                return ResourceManager.GetString("OverlayCDFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t finish operation.
        /// </summary>
        public static string OverlayCDFailTitle {
            get {
                return ResourceManager.GetString("OverlayCDFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try to change your palette name or check the connection.
        /// </summary>
        public static string OverlayCPFailedText {
            get {
                return ResourceManager.GetString("OverlayCPFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string OverlayCPFailedTitle {
            get {
                return ResourceManager.GetString("OverlayCPFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You succesfully upload your color palette.
        /// </summary>
        public static string OverlayCPSuccesText {
            get {
                return ResourceManager.GetString("OverlayCPSuccesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string OverlayCPSuccesTitle {
            get {
                return ResourceManager.GetString("OverlayCPSuccesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You succesufully upload your data. Please wait for it to be processed..
        /// </summary>
        public static string OverlayMFSuccesText {
            get {
                return ResourceManager.GetString("OverlayMFSuccesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string OverlayMFSuccesTitle {
            get {
                return ResourceManager.GetString("OverlayMFSuccesTitle", resourceCulture);
            }
        }
    }
}
