//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapWebSite.Resources.text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapWebSite.Resources.text.TextDictionary", typeof(TextDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HMenuCPTitle {
            get {
                return ResourceManager.GetString("HMenuCPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HMenuCreatePalette {
            get {
                return ResourceManager.GetString("HMenuCreatePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HMenuLogout {
            get {
                return ResourceManager.GetString("HMenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HMenuSettings {
            get {
                return ResourceManager.GetString("HMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HMenuUploadPoints {
            get {
                return ResourceManager.GetString("HMenuUploadPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LBackButton {
            get {
                return ResourceManager.GetString("LBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        public static string LFirstNameInput {
            get {
                return ResourceManager.GetString("LFirstNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name.
        /// </summary>
        public static string LLastNameInput {
            get {
                return ResourceManager.GetString("LLastNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an account? Click here to use the application without account.
        /// </summary>
        public static string LLoginAnonymousLink {
            get {
                return ResourceManager.GetString("LLoginAnonymousLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LLoginButton {
            get {
                return ResourceManager.GetString("LLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your credentials in the texboxes bellow to use the app &lt;br&gt;If you do not have an account, register.
        /// </summary>
        public static string LLoginMessage {
            get {
                return ResourceManager.GetString("LLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LLoginTitle {
            get {
                return ResourceManager.GetString("LLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string LPasswordInput {
            get {
                return ResourceManager.GetString("LPasswordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LRegisterButton {
            get {
                return ResourceManager.GetString("LRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to use the application. Enter the credentials bellow.
        /// </summary>
        public static string LRegisterMessage {
            get {
                return ResourceManager.GetString("LRegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LRegisterTitle {
            get {
                return ResourceManager.GetString("LRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string LSubmitRegisterButton {
            get {
                return ResourceManager.GetString("LSubmitRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string LUsernameInput {
            get {
                return ResourceManager.GetString("LUsernameInput", resourceCulture);
            }
        }
    }
}
