//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapWebSite.Resources.text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapWebSite.Resources.text.TextDictionary", typeof(TextDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassandra server.
        /// </summary>
        public static string CMSCassandra {
            get {
                return ResourceManager.GetString("CMSCassandra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoserver WMTS.
        /// </summary>
        public static string CMSGeoserver {
            get {
                return ResourceManager.GetString("CMSGeoserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid map.
        /// </summary>
        public static string CMTHybrid {
            get {
                return ResourceManager.GetString("CMTHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite map.
        /// </summary>
        public static string CMTSatelitte {
            get {
                return ResourceManager.GetString("CMTSatelitte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points size.
        /// </summary>
        public static string CPSLabel {
            get {
                return ResourceManager.GetString("CPSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        public static string HMenuAboutText {
            get {
                return ResourceManager.GetString("HMenuAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the tool below to create a color palette.&lt;br /&gt;
        ///                Click the bar if you want to create a new color
        ///                and drag dots left or right to set the intervals.
        /// </summary>
        public static string HMenuCPArticle1 {
            get {
                return ResourceManager.GetString("HMenuCPArticle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your creation need a name :) chose it carefully, it must be &lt;b&gt;unique&lt;/b&gt;..
        /// </summary>
        public static string HMenuCPArticle2 {
            get {
                return ResourceManager.GetString("HMenuCPArticle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are almost done if you look here :) just press the button below if you&apos;re done..
        /// </summary>
        public static string HMenuCPArticle3 {
            get {
                return ResourceManager.GetString("HMenuCPArticle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string HMenuCPClosePicker {
            get {
                return ResourceManager.GetString("HMenuCPClosePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max. value.
        /// </summary>
        public static string HMenuCPMaxValueLabel {
            get {
                return ResourceManager.GetString("HMenuCPMaxValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min. value.
        /// </summary>
        public static string HMenuCPMinValueLabel {
            get {
                return ResourceManager.GetString("HMenuCPMinValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter a name....
        /// </summary>
        public static string HMenuCPNameInput {
            get {
                return ResourceManager.GetString("HMenuCPNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors picker panel.
        /// </summary>
        public static string HMenuCPPanelTitle {
            get {
                return ResourceManager.GetString("HMenuCPPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string HMenuCPSubmitButton {
            get {
                return ResourceManager.GetString("HMenuCPSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose colors.
        /// </summary>
        public static string HMenuCPSubtitle1 {
            get {
                return ResourceManager.GetString("HMenuCPSubtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a name.
        /// </summary>
        public static string HMenuCPSubtitle2 {
            get {
                return ResourceManager.GetString("HMenuCPSubtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string HMenuCPSubtitle3 {
            get {
                return ResourceManager.GetString("HMenuCPSubtitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string HMenuCPTemplatesTitle {
            get {
                return ResourceManager.GetString("HMenuCPTemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your own color palette.
        /// </summary>
        public static string HMenuCPTitleText {
            get {
                return ResourceManager.GetString("HMenuCPTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create palette.
        /// </summary>
        public static string HMenuCreatePaletteText {
            get {
                return ResourceManager.GetString("HMenuCreatePaletteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to login.
        /// </summary>
        public static string HMenuLogoutText {
            get {
                return ResourceManager.GetString("HMenuLogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HMenuSettingsText {
            get {
                return ResourceManager.GetString("HMenuSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a text file which contains points and upload them on server. &lt;br /&gt;
        ///            The name which you chose must be unique.
        ///            Dataset will be available for display after a service will process the text file..
        /// </summary>
        public static string HMenuUPInstructionText {
            get {
                return ResourceManager.GetString("HMenuUPInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload points.
        /// </summary>
        public static string HMenuUploadPointsText {
            get {
                return ResourceManager.GetString("HMenuUploadPointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert dataset name....
        /// </summary>
        public static string HMenuUPNameInput {
            get {
                return ResourceManager.GetString("HMenuUPNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file.
        /// </summary>
        public static string HMenuUPSelectFileButton {
            get {
                return ResourceManager.GetString("HMenuUPSelectFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload points.
        /// </summary>
        public static string HMenuUPTitle {
            get {
                return ResourceManager.GetString("HMenuUPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string HMenuUPUploadButton {
            get {
                return ResourceManager.GetString("HMenuUPUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file is required.....
        /// </summary>
        public static string HMenuUPWarningText {
            get {
                return ResourceManager.GetString("HMenuUPWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Geoserver layer.
        /// </summary>
        public static string HMenuUseGeoserverLayerText {
            get {
                return ResourceManager.GetString("HMenuUseGeoserverLayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new window to display the graph and points details. Window is persistent and can be closed anytime..
        /// </summary>
        public static string HPI_TOOLTIP_PlotWindow {
            get {
                return ResourceManager.GetString("HPI_TOOLTIP_PlotWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deformation rate.
        /// </summary>
        public static string HPIDeformationRateText {
            get {
                return ResourceManager.GetString("HPIDeformationRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated def. rate.
        /// </summary>
        public static string HPIEstimatedDefRateText {
            get {
                return ResourceManager.GetString("HPIEstimatedDefRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated height.
        /// </summary>
        public static string HPIEstimatedHeightText {
            get {
                return ResourceManager.GetString("HPIEstimatedHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HPIHeightText {
            get {
                return ResourceManager.GetString("HPIHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string HPIIDText {
            get {
                return ResourceManager.GetString("HPIIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string HPILatitudeText {
            get {
                return ResourceManager.GetString("HPILatitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string HPILongitudeText {
            get {
                return ResourceManager.GetString("HPILongitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plot to display.
        /// </summary>
        public static string HPINoPlotText {
            get {
                return ResourceManager.GetString("HPINoPlotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation.
        /// </summary>
        public static string HPIStandardDeviationText {
            get {
                return ResourceManager.GetString("HPIStandardDeviationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate info.
        /// </summary>
        public static string HPITitleText {
            get {
                return ResourceManager.GetString("HPITitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deformation rate range.
        /// </summary>
        public static string HPSCDDefRateLabel {
            get {
                return ResourceManager.GetString("HPSCDDefRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height range.
        /// </summary>
        public static string HPSCDHeightLabel {
            get {
                return ResourceManager.GetString("HPSCDHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected dataset info.
        /// </summary>
        public static string HPSCDInfoTitleText {
            get {
                return ResourceManager.GetString("HPSCDInfoTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string HPSCDPreviewButton {
            get {
                return ResourceManager.GetString("HPSCDPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type here to search....
        /// </summary>
        public static string HPSCDSearchInput {
            get {
                return ResourceManager.GetString("HPSCDSearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation range.
        /// </summary>
        public static string HPSCDStdDevLabel {
            get {
                return ResourceManager.GetString("HPSCDStdDevLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose dataset.
        /// </summary>
        public static string HPSCDTitleText {
            get {
                return ResourceManager.GetString("HPSCDTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string HPSCDUseButton {
            get {
                return ResourceManager.GetString("HPSCDUseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette name.
        /// </summary>
        public static string HPSCPHead1 {
            get {
                return ResourceManager.GetString("HPSCPHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string HPSCPHead2 {
            get {
                return ResourceManager.GetString("HPSCPHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string HPSCPHead3 {
            get {
                return ResourceManager.GetString("HPSCPHead3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string HPSCPPreviewButton {
            get {
                return ResourceManager.GetString("HPSCPPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type here to search.
        /// </summary>
        public static string HPSCPSearchText {
            get {
                return ResourceManager.GetString("HPSCPSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose palette.
        /// </summary>
        public static string HPSCPTitle {
            get {
                return ResourceManager.GetString("HPSCPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string HPSCPUseButton {
            get {
                return ResourceManager.GetString("HPSCPUseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose the criterium of points color visualisation.
        /// </summary>
        public static string HTM_TOOLTIP_ColorCriteria {
            get {
                return ResourceManager.GetString("HTM_TOOLTIP_ColorCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose the type of the displayed map by selecting an option from the dropdown .
        /// </summary>
        public static string HTM_TOOLTIP_MapType {
            get {
                return ResourceManager.GetString("HTM_TOOLTIP_MapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the range input to change the size of the displayed points.
        /// </summary>
        public static string HTM_TOOLTIP_PointsSize {
            get {
                return ResourceManager.GetString("HTM_TOOLTIP_PointsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose the data source for points layer. This option can enable/disable other functionalities available for data points..
        /// </summary>
        public static string HTM_TOOLTIP_PointsSource {
            get {
                return ResourceManager.GetString("HTM_TOOLTIP_PointsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an adress or details about a place and move the map view on that place.
        /// </summary>
        public static string HTM_TOOLTIP_Search {
            get {
                return ResourceManager.GetString("HTM_TOOLTIP_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselected.
        /// </summary>
        public static string HTMDefaultDataset {
            get {
                return ResourceManager.GetString("HTMDefaultDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset name:.
        /// </summary>
        public static string HTMSelectedDataset {
            get {
                return ResourceManager.GetString("HTMSelectedDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LBackButton {
            get {
                return ResourceManager.GetString("LBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with email confirmation. Please try the link which you receive again, or contact the support..
        /// </summary>
        public static string LCEFailMessage {
            get {
                return ResourceManager.GetString("LCEFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to login page.
        /// </summary>
        public static string LCEGoToLoginLink {
            get {
                return ResourceManager.GetString("LCEGoToLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You confirmed your email with success! Your account is enabled, it can be used to login in application..
        /// </summary>
        public static string LCESuccessMessage {
            get {
                return ResourceManager.GetString("LCESuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        public static string LFirstNameInput {
            get {
                return ResourceManager.GetString("LFirstNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name.
        /// </summary>
        public static string LLastNameInput {
            get {
                return ResourceManager.GetString("LLastNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login. Your account was not activated, please check your email and activate the account..
        /// </summary>
        public static string LLoginActivateAccountMessage {
            get {
                return ResourceManager.GetString("LLoginActivateAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an account? Click here to use the application without account.
        /// </summary>
        public static string LLoginAnonymousLink {
            get {
                return ResourceManager.GetString("LLoginAnonymousLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LLoginButton {
            get {
                return ResourceManager.GetString("LLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your credentials in the texboxes bellow to use the app &lt;br&gt;If you do not have an account, register.
        /// </summary>
        public static string LLoginMessage {
            get {
                return ResourceManager.GetString("LLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LLoginTitle {
            get {
                return ResourceManager.GetString("LLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login. Please check the username or password.
        /// </summary>
        public static string LLoginWrongUsernameOrPasswordMessage {
            get {
                return ResourceManager.GetString("LLoginWrongUsernameOrPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activation link.
        /// </summary>
        public static string LRegisterActivationLinkInput {
            get {
                return ResourceManager.GetString("LRegisterActivationLinkInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation link.
        /// </summary>
        public static string LRegisterActivationLinkLabel {
            get {
                return ResourceManager.GetString("LRegisterActivationLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LRegisterButton {
            get {
                return ResourceManager.GetString("LRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string LRegisterEmailInput {
            get {
                return ResourceManager.GetString("LRegisterEmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LRegisterEmailLabel {
            get {
                return ResourceManager.GetString("LRegisterEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new account. Change the username and try again please..
        /// </summary>
        public static string LRegisterFailMessage {
            get {
                return ResourceManager.GetString("LRegisterFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new account. Your password must contain at least one digit..
        /// </summary>
        public static string LRegisterFailMessageDigit {
            get {
                return ResourceManager.GetString("LRegisterFailMessageDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new account. Your password must contain at least one non letter character or digit..
        /// </summary>
        public static string LRegisterFailMessageLetterOrDigit {
            get {
                return ResourceManager.GetString("LRegisterFailMessageLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new account. Your password length must be at least 6 characters.
        /// </summary>
        public static string LRegisterFailMessagePasswordLen {
            get {
                return ResourceManager.GetString("LRegisterFailMessagePasswordLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new account.  Your password must contain at least one uppercase letter..
        /// </summary>
        public static string LRegisterFailMessageUppercase {
            get {
                return ResourceManager.GetString("LRegisterFailMessageUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of your input is not a valid email format.
        /// </summary>
        public static string LRegisterInvalidEmailFormatInputMessage {
            get {
                return ResourceManager.GetString("LRegisterInvalidEmailFormatInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to use an existing email.
        /// </summary>
        public static string LRegisterInvalidEmailInputMessage {
            get {
                return ResourceManager.GetString("LRegisterInvalidEmailInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not valid. It must contain at least one digit.
        /// </summary>
        public static string LRegisterInvalidPasswordInputMessage_Digit {
            get {
                return ResourceManager.GetString("LRegisterInvalidPasswordInputMessage_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not valid. It must be at least 6 characters long.
        /// </summary>
        public static string LRegisterInvalidPasswordInputMessage_Length {
            get {
                return ResourceManager.GetString("LRegisterInvalidPasswordInputMessage_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not valid. It must contain at least a non letter and a digit.
        /// </summary>
        public static string LRegisterInvalidPasswordInputMessage_LetterOrDigit {
            get {
                return ResourceManager.GetString("LRegisterInvalidPasswordInputMessage_LetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not valid. It must containt at least a uppercase letter.
        /// </summary>
        public static string LRegisterInvalidPasswordInputMessage_Uppercase {
            get {
                return ResourceManager.GetString("LRegisterInvalidPasswordInputMessage_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to use an existing username.
        /// </summary>
        public static string LRegisterInvalidUsernameInputMessage {
            get {
                return ResourceManager.GetString("LRegisterInvalidUsernameInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to use the application. Enter the credentials bellow.
        /// </summary>
        public static string LRegisterMessage {
            get {
                return ResourceManager.GetString("LRegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LRegisterNameLabel {
            get {
                return ResourceManager.GetString("LRegisterNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm password.
        /// </summary>
        public static string LRegisterPasswordConfirmInput {
            get {
                return ResourceManager.GetString("LRegisterPasswordConfirmInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string LRegisterPasswordInput {
            get {
                return ResourceManager.GetString("LRegisterPasswordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LRegisterPasswordLabel {
            get {
                return ResourceManager.GetString("LRegisterPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You registered with success!.
        /// </summary>
        public static string LRegisterSuccessMessage {
            get {
                return ResourceManager.GetString("LRegisterSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LRegisterTitle {
            get {
                return ResourceManager.GetString("LRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LRegisterUsernameLabel {
            get {
                return ResourceManager.GetString("LRegisterUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string LSubmitRegisterButton {
            get {
                return ResourceManager.GetString("LSubmitRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string LUsernameInput {
            get {
                return ResourceManager.GetString("LUsernameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chosed an existent name for your dataset. Please chose another.
        /// </summary>
        public static string OverlayCDFailText {
            get {
                return ResourceManager.GetString("OverlayCDFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t finish operation.
        /// </summary>
        public static string OverlayCDFailTitle {
            get {
                return ResourceManager.GetString("OverlayCDFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try to change your palette name or check the connection.
        /// </summary>
        public static string OverlayCPFailedText {
            get {
                return ResourceManager.GetString("OverlayCPFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string OverlayCPFailedTitle {
            get {
                return ResourceManager.GetString("OverlayCPFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You succesfully upload your color palette.
        /// </summary>
        public static string OverlayCPSuccesText {
            get {
                return ResourceManager.GetString("OverlayCPSuccesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string OverlayCPSuccesTitle {
            get {
                return ResourceManager.GetString("OverlayCPSuccesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You succesufully upload your data. Please wait for it to be processed..
        /// </summary>
        public static string OverlayMFSuccesText {
            get {
                return ResourceManager.GetString("OverlayMFSuccesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string OverlayMFSuccesTitle {
            get {
                return ResourceManager.GetString("OverlayMFSuccesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successufuly registered in application. An confirmation link has been send at {0} for activating the account..
        /// </summary>
        public static string RegisterCompleteMessage {
            get {
                return ResourceManager.GetString("RegisterCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please confirm your account by clicking the following link: &lt;/p&gt; &lt;a href=&quot;{0}&quot;&gt;Confirm your account&lt;/a&gt;.
        /// </summary>
        public static string RegisterConfirmationEmailBody {
            get {
                return ResourceManager.GetString("RegisterConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the account. The email which you introduced couldn&apos;t be used for account confirmation. Try again later..
        /// </summary>
        public static string RegisterConfirmationEmailFailed {
            get {
                return ResourceManager.GetString("RegisterConfirmationEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSTOOL register - Confirm your account.
        /// </summary>
        public static string RegisterConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("RegisterConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for a place....
        /// </summary>
        public static string SCPlaceholder {
            get {
                return ResourceManager.GetString("SCPlaceholder", resourceCulture);
            }
        }
    }
}
